#!/bin/sh
# $Id: DEINSTALL 147690 2007-01-03 15:01:08Z seanb $

YAT_CONF_DIR="@PKG_SYSCONFDIR@"
DEFAULT_ADMIN="@DEFAULT_ADMIN@"
MIN="@YATSVR_MINGID@"
MAX="@YATSVR_MAXGID@"

case "$2" in
DEINSTALL)

	admin=`${CAT} ${YAT_CONF_DIR}/.admin`
	if [ "$admin" = "${DEFAULT_ADMIN}" ]; then
		${RM} -f ${YAT_CONF_DIR}/.admin
	fi
	${AWK} -F: '$1 !~ /^no/ { if ($3 < '$MIN' || $3 > '$MAX') print $1}' \
		/etc/group > /tmp/hidden-group
	if ${CMP} -s ${YAT_CONF_DIR}/.hidden-group /tmp/hidden-group; then
		${RM} -f ${YAT_CONF_DIR}/.hidden-group
	fi
	${RM} -f /tmp/hidden-group
	${RM} -f ${YAT_CONF_DIR}/*\~old
	;;
esac
