#!/bin/sh
# $Id: INSTALL 147690 2007-01-03 15:01:08Z seanb $

YAT_CONF_DIR="@PKG_SYSCONFDIR@"
DEFAULT_ADMIN="@DEFAULT_ADMIN@"
MIN="@YATSVR_MINGID@"
MAX="@YATSVR_MAXGID@"

case ${STAGE} in
POST-INSTALL)
	if [ ! -f ${YAT_CONF_DIR}/.admin ]; then
		echo ${DEFAULT_ADMIN} > ${YAT_CONF_DIR}/.admin
		${CHMOD} 0600 ${YAT_CONF_DIR}/.admin
	fi
	# hack for restrict groups
	${AWK} -F: '$1 !~ /^no/ { if ($3 < '$MIN' || $3 > '$MAX') print $1}' \
		/etc/group > ${YAT_CONF_DIR}/.hidden-group
	${CHMOD} 0600 ${YAT_CONF_DIR}/.hidden-group
	;;
esac
